### ISSUE TITLE
APM SOAP metrics webservice to REST

### ISSUE THREAD

**Issue by vangu02** [CA-APM/-new-repository-request#11]
What does it do? - it pulls CA APM metrics via REST and returns a json

How does it work? Uses a lightweight jersey http server with REST support (grizzly)

What versions of APM does it work with? 9.7 & 10.0

What versions of APM has it been tested with? tested with apm 9.7 & 10.0

Do you have any automated tests? no

Provide the link to your public GitHub repository so we can clone your content. 
https://github.com/vangu02/SOAP2REST

**Comment by ggrossbe** [comment]
Done. Thanks, Guy!
