### ISSUE TITLE
New FieldPack request

### ISSUE THREAD

**Issue by ayork22** [CA-APM/-new-repository-request#13]
Hey FieldPack team.  I have a new FP developed to monitor Stash/BitBucket.  Reading through docs on the process for publishing a new FP I believe I am starting in the right place.  Please let me know if you need anything else from me or if I'm going down the wrong path. 

**GitHub link to project.**
https://github.com/ayork22/ca-apm-fieldpack-Stash.BitBucket.git

Thanks!!!

**Comment by ggrossbe** [comment]
Cool!
1. Please add a license file (Apache 2.0 or Eclipse) to your repo.
2. Do not check in binaries (class files, jars, zips, etc)! The repository should only contain the source, build scripts, resources (like config files) and documentation. Run “mvn/make clean” before you commit and add your binary, lib, … directories to .gitignore!

For dependencies use maven (https://maven.apache.org/). See some of our projects on https://github-isl-01.ca.com/APMSWAT as examples. Copy/merge the settings.xml from FieldPackSetup.zip to your ~/.m2 directory to link to our internal artifactory servers and maven mirrors. See Eclipse One-Time Setup for more details.

To distribute binaries you can create a release on github and put the binaries there: https://help.github.com/articles/creating-releases/. You can then link to ./releases from the README. 

Ciao,
Guenter

**Comment by ayork22** [comment]
Hey Guenter,

First time running through this, so I had a few pain points.  I created a new Maven project following the instructions and I think I have in the correct format now.  Also I created a new GitHub repository as noted below.

Updated GitHub repository: https://github.com/ayork22/ca.apm.fieldpacks.stash.bitbucket

Alex York
Services Consultant
CA Technologies | 2060 Briargate Parkway Suite 310 | Colorado Springs, CO 80920
Mobile: +1 303 909-1519 | Alex.York@ca.com
mailto:Alex.York@ca.com[Description: CA]http://www.ca.com/us/default.aspx[Description: Twitter]http://twitter.com/CAInc[Description: Slideshare]http://www.slideshare.net/cainc[Description: Facebook]https://www.facebook.com/CATechnologies[Description: YouTube]http://www.youtube.com/user/catechnologies[Description: LinkedIn]http://www.linkedin.com/company/1372?goback=.cps_1244823420724_1[Description: Google+]https://plus.google.com/+CATechnologies[Description: Google+]http://www.ca.com/us/rss.aspx?intcmp=footernav

From: Guenter Grossberger
Reply-To: CA-APM/-new-repository-request
Date: Monday, February 1, 2016 at 12:02 PM
To: CA-APM/-new-repository-request
Cc: "York, Alex G"
Subject: Re: [-new-repository-request] New FieldPack request (#13)
1.  Do not check in binaries (class files, jars, zips, etc)! The repository should only contain the source, build scripts, resources (like config files) and documentation. Run “mvn/make clean” before you commit and add your binary, lib, … directories to .gitignore!

**Comment by ggrossbe** [comment]
Hi Alex,

no problem. I appreciate that you share your code!

If it's a maven project please also check in the pom.xml.

You didn't have to create a new project for that. You coudl just have removed the binary files and added the new ones. That's what a versioning control system is for ;)

Ciao,
Guenter

**Comment by ayork22** [comment]
Yep, still getting my head around GIT & its functionality.

Quick question on the pom.xml (Attached).  I had it checked in, but I remembered it had my PMFKey & Password located within the xml, which I’m sure should not be shared with the world :)   Am I using the incorrect pom.xml or do I just not fill in my PMFKEY & Password?

<wikiPageId>${wiki.page.id}</wikiPageId>

<pmfKey>yoral01</pmfKey>

<pmfPassword>PASSWORD</pmfPassword>

Alex York
Services Consultant
CA Technologies | 2060 Briargate Parkway Suite 310 | Colorado Springs, CO 80920
Mobile: +1 303 909-1519 | Alex.York@ca.com
mailto:Alex.York@ca.com[Description: CA]http://www.ca.com/us/default.aspx[Description: Twitter]http://twitter.com/CAInc[Description: Slideshare]http://www.slideshare.net/cainc[Description: Facebook]https://www.facebook.com/CATechnologies[Description: YouTube]http://www.youtube.com/user/catechnologies[Description: LinkedIn]http://www.linkedin.com/company/1372?goback=.cps_1244823420724_1[Description: Google+]https://plus.google.com/+CATechnologies[Description: Google+]http://www.ca.com/us/rss.aspx?intcmp=footernav

From: Guenter Grossberger
Reply-To: CA-APM/-new-repository-request
Date: Monday, February 1, 2016 at 9:23 PM
To: CA-APM/-new-repository-request
Cc: "York, Alex G"
Subject: Re: [-new-repository-request] New FieldPack request (#13)

Hi Alex,

no problem. I appreciate that you share your code!

If it's a maven project please also check in the pom.xml.

You didn't have to create a new project for that. You coudl just have removed the binary files and added the new ones. That's what a versioning control system is for ;)

Ciao,
Guenter

**Comment by ayork22** [comment]
Hey Guenter... lets try this again.  I made a few updates & got them uploaded to GitHub.  I need to update the README as I updated the project to run as a stateful program.  I should get that updated here shortly.

I moved it back to a regular java project as I was having some struggles w/ the Maven project (no experience w/ Maven till now).

**Project:**
https://github.com/ayork22/ca.apm.fieldpacks.stash.bitbucket

Alex York
Services Consultant
CA Technologies | 2060 Briargate Parkway Suite 310 | Colorado Springs, CO 80920
Mobile: +1 303 909-1519 | Alex.York@ca.com
mailto:Alex.York@ca.com[Description: CA]http://www.ca.com/us/default.aspx[Description: Twitter]http://twitter.com/CAInc[Description: Slideshare]http://www.slideshare.net/cainc[Description: Facebook]https://www.facebook.com/CATechnologies[Description: YouTube]http://www.youtube.com/user/catechnologies[Description: LinkedIn]http://www.linkedin.com/company/1372?goback=.cps_1244823420724_1[Description: Google+]https://plus.google.com/+CATechnologies[Description: Google+]http://www.ca.com/us/rss.aspx?intcmp=footernav

From: Guenter Grossberger
Reply-To: CA-APM/-new-repository-request
Date: Monday, February 1, 2016 at 9:23 PM
To: CA-APM/-new-repository-request
Cc: "York, Alex G"
Subject: Re: [-new-repository-request] New FieldPack request (#13)

Hi Alex,

no problem. I appreciate that you share your code!

If it's a maven project please also check in the pom.xml.

You didn't have to create a new project for that. You coudl just have removed the binary files and added the new ones. That's what a versioning control system is for ;)

Ciao,
Guenter
