### ISSUE TITLE
CA APM Wily ActiveMQ Agent/plugin

### ISSUE THREAD

**Issue by 27sumit** [CA-APM/-new-repository-request#14]
Hi there,
Is it possible to develop CA APM Wily agent/plugin which can monitor and extract deep dive active mq metrics?

thanks
Sumit

**Comment by hrahmed** [comment]
Sumit there is a field pack that uses bytcode instrumentation to monitor active MQ, this gives you much deeper transactional visibility into the transactions.  Check with presales or open a support ticket to get the field pack.

regards,
haroon

**Comment by 27sumit** [comment]
thanks Haroon

**Comment by hrahmed** [comment]
now worries Summit, going to close this issue.
