### ISSUE TITLE
new request

### ISSUE THREAD

**Issue by barsutka** [CA-APM/-new-repository-request#16]
Hello,

I want to create a new repo for apm-metrics-simulator project that I've started to work on.
It's a JMeter script and few CSV files. I'm using the REST point of the EPAgent to create metrics in Introscope.
It should work with any APM version that has EPAgent with REST endpoint - the one that supports JSON.
I've tested it with APM 10.5.2.
Once I have your confirmation - I'll open up the project to the public on my github org.

Thanks in advance,
Maxim.

**Comment by ggrossbe** [comment]
Hi Maxim,

Great! Just make sure you have a README.md like [this template](https://github.com/CA-APM/-new-repository-request/blob/master/README-template.md) and either EPL 2.0 or Apache License. If there is any third party code include appropriate notice.

Ciao,
Guenter

**Comment by barsutka** [comment]
Hi Guenter,
Here is my repository that you can clone into CA-APM org - https://github.com/barsutka/apm-metrics-simulator.

Thanks,
Maxim.

**Comment by ggrossbe** [comment]
forked it on Feb 22
