### ISSUE TITLE
New request: ActiveMQ broker restful EPA script

### ISSUE THREAD

**Issue by guenter14** [CA-APM/-new-repository-request#3]
### What does it do?

This field pack pulls JMX metrics from ActiveMQ broker into CA APM.
### How does it work? (EPA plugin, PBD file, name formatter, etc.)

A python script pulls JMX data from an ActiveMQ broker via the Jolokia http interface and sends it to an EPAgent using the rest interface. I also created a typeviewer for it.
### What versions of APM does it work with?

APM 9.7.1 (restful EPA)
### What versions of APM has it been tested with?

APM 9.7.1 (restful EPA)
### What versions of third party software does it work with and has it been tested with?

ActiveMQ (http://activemq.apache.org/) 5.10.0
### Provide the link to your public GitHub repository so we can clone your content.

https://github.com/guenter14/ca-apm-fieldpack-activemq-broker.git

**Comment by ggrossbe** [comment]
Ok. We published it. Thank you, Guenter
