### ISSUE TITLE
New Request: nginx EPAgent

### ISSUE THREAD

**Issue by tmcgaughey** [CA-APM/-new-repository-request#4]
What does it do?

This provides nginx metrics to a CA APM EPAgent.

How does it work? (EPA plugin, PBD file, name formatter, etc.)

A node.js script will query the nginx stats URL and send JSON formatted output to an EPAgent using the REST interface.  Configure param.json to indicate the nginx URL and the EPAgent information.  Run by using "node index"

What versions of APM does it work with?

APM 9.7.1 (restful EPA)

What versions of APM has it been tested with?

APM 9.7.1 (restful EPA)

What versions of third party software does it work with and has it been tested with?

nginx 1.6.3.  The --with-http_stub_status_module flag is required in the nginx -V output.
node v0.10.38

Provide the link to your public GitHub repository so we can clone your content.

https://github.com/tmcgaughey/nginx-epa.git

**Comment by ggrossbe** [comment]
Hi Tim,

congratulations! The field pack is published as https://github.com/CA-APM/ca-apm-fieldpack-nginx!

Guenter
