### ISSUE TITLE
Docker field pack

### ISSUE THREAD

**Issue by guenter14** [CA-APM/-new-repository-request#5]
### What does it do?

Restful EPAgent script (python) to monitor Docker via Remote API.
### How does it work? (EPA plugin, PBD file, name formatter, etc.)

Restful EPAgent script
### What versions of APM does it work with?

APM 9.7.1+
### What versions of APM has it been tested with?

APM 9.7.1
### Do you have any automated tests? Describe them or attach test results.

no
### Provide the link to your public GitHub repository so we can clone your content.

https://github.com/guenter14/ca-apm-fieldpack-docker.git

**Comment by ggrossbe** [comment]
Published.
