### ISSUE TITLE
Docker performance monitoring

### ISSUE THREAD

**Issue by bhaab01** [CA-APM/-new-repository-request#6]
### What does it do?

This is an application which accesses Docker's internal infrastructure through HTTP and post performance metrics of various docker containers to APM using EPA Rest interface  
### How does it work? (EPA plugin, PBD file, name formatter, etc.)

a) Access docker URLs through http remotely from a Java program 
For eg. the below URL returns all the docker images inside a docker host
   http://host_name:port_no/containers/json?all=1

Similarly, we have several URLs which provide some useful information about the performance of various containers. 
For more details, please refer to : 
  https://docs.docker.com/reference/api/docker_remote_api_v1.18/

b) The above query returns data in JSON format. We parse it, calculate some useful APM metrics like CPU Utilization ( %) , Memory Utilization ( %) , Running versus Stopped docker images etc 

c) Post data in JSON format to EPA Rest inteface

d) Information related to docker hostname, port, EPAgent host/port and polling frequency will be obtained from docker.properties
##### Pre-requisite

Docker Application needs to be started with -H parameter so that it can bind Docker to another host/port or a Unix socket ( both http and https ) 

For eg.

```
 docker -d --tlsverify --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem -H=0.0.0.0:2376
```
### What versions of APM does it work with?

APM 9.7.1 onwards
### What versions of APM has it been tested with?

APM 9.7.1 
### Do you have any automated tests? Describe them or attach test results.

No
### Provide the link to your public GitHub repository so we can clone your content.

https://github.com/bhaab01/DockerMonitoring
#### Docker host level Metrics and Typeviews

![container](https://cloud.githubusercontent.com/assets/12104260/8067606/b85849a6-0ee6-11e5-8ce7-d1c200803b31.png)
#### Each Container level  Metrics and Typeviews

![hostlevel](https://cloud.githubusercontent.com/assets/12104260/8067579/8821e2ec-0ee6-11e5-8965-eac2ee81aa98.png)
### Additional Information :

This was discussed on another thread about the difference on Guenter's fieldpack located at 
https://cawiki.ca.com/display/APMFIELDPACKS/Docker+Field+Pack
https://github-isl-01.ca.com/APMSWAT/fieldpack.docker

This is my view - 

1)      Guenter’s fieldpack works via https and my solution works via both http and https. For my soln to work, docker administrator need to open a port to listen on a specific IP and Port using –H option, for the fieldpack docker administrator needs to issue an certificate to get root access and in turn getting access on docker.sock file. 
2)      Fieldpack is written on python and mine is written on pure Java 
3)      I have created some “derived” metrics like CPU Utilization , Memory Utilization , Total Packet Dropped and Errors through my Java extention but this is not present currently on Fieldpack but this can be easiliy extended I believe 
4)     The typeview and metric representation is different 
5)     Most probably Guenter’s fieldpack works for a single container (not sure though )and this one can connect to a host and can discover all the underline containers

**Comment by ggrossbe** [comment]
Hi Abhijit,

thank you for your submission. We will review it at the next CA APM Developer Community Steering Committee on 6/17. We will let you know of the progress and come back to you with questions if any.

Ciao,
Guenter

**Comment by ggrossbe** [comment]
Hi Abhijit,

can you create a separate wiki page (see https://cawiki.ca.com/display/APMFIELDPACKS/APM+Field+Pack+Check+List) for your field pack and copy the above information into it.

Ciao,
Guenter

**Comment by bhaab01** [comment]
Hi Guenter
Will this information good enough ? I don't know what do I need to fill up for few of the sections in the page like issue tracker etc
https://cawiki.ca.com/display/APMFIELDPACKS/Docker+Monitoring

Thanks,
Abhijit

**Comment by bhaab01** [comment]
Updated the source code with https support as well : 
Now, this solution will work for both http and https 

https://github.com/bhaab01/DockerMonitoring/blob/master/docker-monitoring-eparest/README.md

Thanks,
Abhijit

**Comment by ggrossbe** [comment]
Hi Abhijit,
I sent you a pull request with the changes I made regarding the license in the source files. Once you pulled my changes I will fork your repo to CA-APM.

Ciao,
Guenter

**Comment by bhaab01** [comment]
Hi Guenter, 
I just pulled the changes 
Thanks,
Abhijit

**Comment by ggrossbe** [comment]
Forked your repo. Congrats, Abhijit!
