### ISSUE TITLE
ca-apm-fieldpack-windows-wmi

### ISSUE THREAD

**Issue by srikns** [CA-APM/-new-repository-request#7]
### What does it do?

Pulls Windows WMI metrics
### How does it work? (EPA plugin, PBD file, name formatter, etc.)

EPA plugin - powershell commands
### What versions of APM does it work with?

9.5,9.6,9.7
### What versions of APM has it been tested with?

all of the above
### Do you have any automated tests? Describe them or attach test results.

nope
### Provide the link to your public GitHub repository so we can clone your content.

https://github.com/srikns/ca-apm-fieldpack-windows-wmi.git

**Comment by ggrossbe** [comment]
Thank you for contributing. This request will be handled in the next FP steering committee.

**Comment by ggrossbe** [comment]
Forked your repo. Thank you for your contribution!
