### ISSUE TITLE
new request

### ISSUE THREAD

**Issue by mirek-turski** [CA-APM/-new-repository-request#8]
### What does it do?

Example scripts that present a way of using APM Command Center RESTful API to automate some typical tasks.
### How does it work? (EPA plugin, PBD file, name formatter, etc.)

Uses various scripting languages and web clients to interact with API provided by APM Command Center Server
### What versions of APM does it work with?

Every version that APM Command Center works with (9.x up), but the scripts do not interact with core APM directly.
### What versions of APM has it been tested with?

APM Command Center 1.1.0.6 (GA) which is the first version with public API.
### Do you have any automated tests? Describe them or attach test results.

No. All scripts were tested manually on various platforms (Windows, a few distros of Linux, some shell scripts were even run on Cygwin).
### Provide the link to your public GitHub repository so we can clone your content.

https://github-isl-01.ca.com/turmi05/ca-apm-acc-api-scripts

**Comment by ggrossbe** [comment]
Hi Miro,

thank you for your contribution. We published the scripts. I sent you a pull request to include the Apache license.
