### ISSUE TITLE
new request: Cloud Foundry Firehose Nozzle to EPA

### ISSUE THREAD

**Issue by tmcgaughey** [CA-APM/-new-repository-request#9]
### What does it do?

Connects to a Cloud Foundry Firehose and send relevant metrics on to an EPAgent via the REST interface.
### How does it work? (EPA plugin, PBD file, name formatter, etc.)

EPA plugin, and Go program
### What versions of APM does it work with?

9.7.1+ RESTful EPA 
### What versions of APM has it been tested with?

9.7 & 10
### Do you have any automated tests? Describe them or attach test results.

No.  I am lazy.
### Provide the link to your public GitHub repository so we can clone your content.

https://github.com/tmcgaughey/epagent-nozzle

**Comment by ggrossbe** [comment]
Hi,
thank you for your submission.
The next steering committee meeting is on Sept, 23. Can you please create an internal Wiki page to describe the field pack?

Ciao,
Guenter

**Comment by ggrossbe** [comment]
Forked to CA-APM. Thank you for your contribution, Tim!
